// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRDiF-7da-FZnLhUeOEPlHqhxRg3R9L5E',
    appId: '1:533538439569:web:03813db8f170ee7b3c9a30',
    messagingSenderId: '533538439569',
    projectId: 'routus-2e2cd',
    authDomain: 'routus-2e2cd.firebaseapp.com',
    storageBucket: 'routus-2e2cd.firebasestorage.app',
    measurementId: 'G-F4RVF979H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg6dASLjm_y65F3ncvw98S4luvMrqOA14',
    appId: '1:533538439569:android:3c1a1e1c73b10eaf3c9a30',
    messagingSenderId: '533538439569',
    projectId: 'routus-2e2cd',
    storageBucket: 'routus-2e2cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFqSChBX_45q2peEuKNas6lT7i3syJfis',
    appId: '1:533538439569:ios:d6e314b0ba7951be3c9a30',
    messagingSenderId: '533538439569',
    projectId: 'routus-2e2cd',
    storageBucket: 'routus-2e2cd.firebasestorage.app',
    iosBundleId: 'com.example.routus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFqSChBX_45q2peEuKNas6lT7i3syJfis',
    appId: '1:533538439569:ios:d6e314b0ba7951be3c9a30',
    messagingSenderId: '533538439569',
    projectId: 'routus-2e2cd',
    storageBucket: 'routus-2e2cd.firebasestorage.app',
    iosBundleId: 'com.example.routus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRDiF-7da-FZnLhUeOEPlHqhxRg3R9L5E',
    appId: '1:533538439569:web:cc55f06e30de21cb3c9a30',
    messagingSenderId: '533538439569',
    projectId: 'routus-2e2cd',
    authDomain: 'routus-2e2cd.firebaseapp.com',
    storageBucket: 'routus-2e2cd.firebasestorage.app',
    measurementId: 'G-PEELWJDDGZ',
  );
}
