// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9dou1GsEd6MLqcf8q35lgr_fwTrbeb24',
    appId: '1:649004395439:web:4c0a422780b72ac4ca1d5a',
    messagingSenderId: '649004395439',
    projectId: 'device-streaming-9b639089',
    authDomain: 'device-streaming-9b639089.firebaseapp.com',
    storageBucket: 'device-streaming-9b639089.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvu499r8nEfiIphCbtmZHfGJXe3lO0nqE',
    appId: '1:649004395439:android:b00df8713d4adfc7ca1d5a',
    messagingSenderId: '649004395439',
    projectId: 'device-streaming-9b639089',
    storageBucket: 'device-streaming-9b639089.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJVP8aYfzOk2cP89WAAm4v2GzY90k3tcM',
    appId: '1:649004395439:ios:d9d6f074c5906194ca1d5a',
    messagingSenderId: '649004395439',
    projectId: 'device-streaming-9b639089',
    storageBucket: 'device-streaming-9b639089.firebasestorage.app',
    iosBundleId: 'com.example.routus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJVP8aYfzOk2cP89WAAm4v2GzY90k3tcM',
    appId: '1:649004395439:ios:d9d6f074c5906194ca1d5a',
    messagingSenderId: '649004395439',
    projectId: 'device-streaming-9b639089',
    storageBucket: 'device-streaming-9b639089.firebasestorage.app',
    iosBundleId: 'com.example.routus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9dou1GsEd6MLqcf8q35lgr_fwTrbeb24',
    appId: '1:649004395439:web:0c51da7336c4239aca1d5a',
    messagingSenderId: '649004395439',
    projectId: 'device-streaming-9b639089',
    authDomain: 'device-streaming-9b639089.firebaseapp.com',
    storageBucket: 'device-streaming-9b639089.firebasestorage.app',
  );
}
